name: ${name}
author: TrueMB
version: ${version}
api-version: 1.16
main: me.truemb.tvc.main.Main

softdepend: [MythicMobs]

commands:
   twitchviewercontrol:
      aliases: tvc
      description: Plugin management Command